<a href="https://colab.research.google.com/github/Tanishqtaluja/Data--Science--NF/blob/main/data_cleaning_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Employment of India Dataset - Data Cleaning Project

In [6]:
from google.colab import files
uploaded = files.upload()

Saving Messy_Employment_India_Dataset.csv to Messy_Employment_India_Dataset (1).csv


## Step 1: Load and Inspect Dataset

In [7]:
import pandas as pd

df = pd.read_csv('Messy_Employment_India_Dataset.csv')
print(df.head())

       Status Age Group    Education    Industry   Location   AI Risk  \
0    EMPLOYED     25_34  high school  Technology      Urban       NaN
1    EMPLOYED     18-24      Diploma     Fintech      rural  moderate
2    EMPLOYED     25_34  High School      Retail      Delhi       Low
3  UNEMPLOYED     18-24      Masters      Retail      Urban       Low
4         NaN     45-54      Diploma     Fintech  Hyderabad       low

   Years of Experience  Monthly Salary (INR) Date Recorded
0                  NaN               40700.0      1/1/2023
1                  NaN               17500.0      1/2/2023
2                 16.0               77600.0      1/3/2023
3                 30.0              100200.0      1/4/2023
4                  9.0               19500.0      1/5/2023


## Step 2: Understand Dataset Structure

In [8]:
print("Rows and Columns:", df.shape)
print(df.columns)
df.info()
df.describe(include="all")

Rows and Columns: (2000, 9)
Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
count,1732,1768,1804,1799,1787,1716,980.000000,1613.000000,2000
unique,6,7,9,8,8,6,NaN,NaN,2000
top,Employed,18 to 24,Bachelors,Retail,Delhi,HIGH,NaN,NaN,6/6/2028
freq,302,262,225,429,233,308,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,15.244898,76886.360818,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.103941,41628.008054,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,5100.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,40700.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,77200.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,112400.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,149900.000000,NaN


## Step 3: Handle Missing Values

In [9]:


df = pd.read_csv("Messy_Employment_India_Dataset.csv")
print(df.isnull().sum())
#print(df.isnull().sum().sum())
#print(df[df.isnull().any(axis=1)])

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64


## Step 4: Remove Duplicate Records

In [10]:
print("Duplicates:", df.duplicated().sum())

df = df.drop_duplicates()

print("After Removal:", df.duplicated().sum())

Duplicates: 0
After Removal: 0

##Step 5:Correct inconsistent formatting and text values

In [11]:
df["Status"] = df["Status"].str.strip().str.title()
df["Education"] = df["Education"].str.strip().str.title()
df["Industry"] = df["Industry"].str.strip().str.title()
df["Location"] = df["Location"].str.strip().str.title()
df["AI Risk"] = df["AI Risk"].str.strip().str.title()

# Standardize Age Group values
df["Age Group"] = df["Age Group"].str.replace("_", "-", regex=False)

# Check cleaned values
print(df.head())

       Status Age Group    Education    Industry   Location   AI Risk  \
0    Employed     25-34  High School  Technology      Urban       NaN
1    Employed     18-24      Diploma     Fintech      Rural  Moderate
2    Employed     25-34  High School      Retail      Delhi       Low
3  Unemployed     18-24      Masters      Retail      Urban       Low
4         NaN     45-54      Diploma     Fintech  Hyderabad       Low

   Years of Experience  Monthly Salary (INR) Date Recorded
0                  NaN               40700.0      1/1/2023
1                  NaN               17500.0      1/2/2023
2                 16.0               77600.0      1/3/2023
3                 30.0              100200.0      1/4/2023
4                  9.0               19500.0      1/5/2023


## Step 6: Fix Data Types

In [ ]:
df['Date Recorded'] = pd.to_datetime(
    df['Date Recorded']
)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   string
 1   Age Group             1768 non-null   string
 2   Education             1804 non-null   string
 3   Industry              1799 non-null   string
 4   Location              1787 non-null   string
 5   AI Risk               1716 non-null   string
 6   Years of Experience   980 non-null    Int64
 7   Monthly Salary (INR)  1613 non-null   Int64
 8   Date Recorded         2000 non-null   datetime64[ns]
dtypes: Int64(2), datetime64[ns](1), string(6)
memory usage: 144.7 KB

# Step 7:Detect and handle outliers

In [16]:
from scipy import stats
df = df[(abs(stats.zscore(df.select_dtypes(include='number'))) < 3).all(axis=1)]

print(df.shape)

(781, 9)


## Step 8: Standardize Column Names

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.lower().str.replace(" ", "_")
print(df.columns)

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_(inr)', 'date_recorded'],
      dtype='object')

## Step 9: Validate Cleaned Data

In [ ]:
print(df.info())

#  missing values
print(df.isnull().sum())

#  duplicate records
print(df.duplicated().sum())

#  first 5 rows
(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB
None
Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64
0

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023


## Step 10: Export Cleaned Dataset

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)
print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!