<a href="https://colab.research.google.com/github/Tanishqtaluja/Data--Science--NF/blob/main/module_2_python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# chapter 1

Data Manipulation with pandas
pandaa
open source python library for data manipulation , analysis and cleaning
build on top of numpy
handle structured data efficently
useddd inn: data cleaning,eda,feature eng

# why we use pandas
handle large dataset, easy to work with csv, excel, sql
,provide fast and flexible data opeartion,
used in data science, ml

# in pandas we have 2 types of data structure ( sensorss reading        timeseries data    Application of series)
series (one dimensional , it contain values and index)

In [ ]:
import pandas as pd

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1)
print(var)
print(type(var))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1,index = ['a','b','c','r','y'])                     # in this we will give the indexing name as a b c r y
print(var)

a     2
b     4
c     6
r     8
y    10
dtype: int64

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1,index = ['a','b','c','r','y'],dtype ="float")           #in this we cahnge the data type
print(var)

a     2.0
b     4.0
c     6.0
r     8.0
y    10.0
dtype: float64

In [ ]:
l1 = [2,4,6,8,10]
var = pd.Series(l1,index = ['a','b','c','r','y'],dtype ="float" ,name = "mylist")       # in this we will change the list name
print(var)

a     2.0
b     4.0
c     6.0
r     8.0
y    10.0
Name: mylist, dtype: float64

In [ ]:
var2 = pd.Series(5,index=[1,2,3,4,5])
print(var2)

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [ ]:
var2 = pd.Series(5,index=[2,4,5,7,8])                                # add both the var having the same index no
var3 = pd.Series(10,index=[2,3,4,5,6])
print(var2+var3)

2    15.0
3     NaN
4    15.0
5    15.0
6     NaN
7     NaN
8     NaN
dtype: float64

In [ ]:
mydic = {
    "name" : ["a","b","c",],
    "roll no": [21,22,33],
    "age" : [44,33,66],                                   # using dic in the series format

}
var4 = pd.Series(mydic)
print(var4)

name          [a, b, c]
roll no    [21, 22, 33]
age        [44, 33, 66]
dtype: object

# Series Operation
s.sum(),
s.mean(),
s.max(),
s.min(),

In [ ]:
myseries = [2,3,4,5,6,]
r= pd.Series(myseries)
Sum = r.sum()
print("sum of series",Sum)

sum of series 20

In [ ]:
myseries = [2,3,4,5,6,]
r= pd.Series(myseries)
Sum = r.mean()
print("mean of series",Sum)

mean of series 4.0

# indexing and slicing
s[0],
s['MATH'],
S[1:3]

# Vectorized Function
s+5,s*2,s-5,s/2,s%5,s**2

In [ ]:
list=[1,2,3,4,5]
ds = pd.Series(list)
ds+5

0     6
1     7
2     8
3     9
4    10
dtype: int64

# Pandas Data Frame
it is a two dimensional label  data structure in pandas that stores data in rows and colums , similar to excel and sql shet
# key eatures\
 - hetrogenous data support
 - labeled rows and colums
 - efficient data manipulation
 - missing values handle





# Data frame component
 - row
 - colums
 - index
 - values
## Dataframe Operations
- df.head()                first 5 rows
- df.tail()                last 5 rows
- df.sample()              rndom row
- df.info()                columns names, data types,non null
- df.shape()               rows, columns
- df.columns()             
- df.index()               info index
- df.dtypes()              data type of each columns

## Data manipulattion  operations
add and remove
- df.['bonus'] = df['salary']*0.1
- df.drop('bonus',axis=1)


# Filtering data

# in series only one column (max)   rows multiple
# in data frame only one column (min)  rows multiple

In [ ]:
import pandas as pd

In [ ]:
list_1 = [2,4,6,8,10]
var=pd.DataFrame(list_1)
print(var)
print(type(var))

    0
0   2
1   4
2   6
3   8
4  10
<class 'pandas.core.frame.DataFrame'>

In [ ]:
info = {
    "name" : "Tanishq",
    "Age" : 32,
    "maths" : 55,
    "Status" : True
}
df = pd.DataFrame(info, index=['A','B','C'])
print(df)

      name  Age  maths  Status
A  Tanishq   32     55    True
B  Tanishq   32     55    True
C  Tanishq   32     55    True

In [ ]:
info = {
    "name" : ["Tanishq","tanishka","kashish","arpit"],
    "Age" :  [32,43,54,53],
    "maths" : [55,66,78,88],
    "Status" : [True,True,False,False],
}
df = pd.DataFrame(info , index=['A','B','C','D'])
print(df)

       name  Age  maths  Status
A   Tanishq   32     55    True
B  tanishka   43     66    True
C   kashish   54     78   False
D     arpit   53     88   False

In [ ]:
info = {
    "name" : ["Tanishq","tanishka","kashish","arpit"],
    "Age" :  [32,43,54,53],
    "maths" : [55,66,78,88],
    "Status" : [True,True,False,False],
}
df = pd.DataFrame(info ,columns=['name','Age'])                  #print all the values which we wriiten
print(df)

       name  Age
0   Tanishq   32
1  tanishka   43
2   kashish   54
3     arpit   53

In [ ]:
info = {
    "name" : ["Tanishq","tanishka","kashish","arpit"],
    "Age" :  [32,43,54,53],
    "maths" : [55,66,78,88],
    "Status" : [True,True,False,False],             # it will print the index value which we given
}
df= pd.DataFrame(info)
print(df['name'][0])

Tanishq

In [ ]:
T=[['A','B','C','D'],['a','b','c','d']]
df=pd.DataFrame(T)                              # print both list in the form of table
print(df)

   0  1  2  3
0  A  B  C  D
1  a  b  c  d

In [ ]:
SR = {
    "S" : pd.Series([2,4,6,8]),
    "r" : pd.Series([3,5,7,9])
}
df= pd.DataFrame(SR)                              #only use df it will create table
#print(df)
df

   S  r
0  2  3
1  4  5
2  6  7
3  8  9

In [ ]:
df=pd.DataFrame({"A": [2,4,6,8],"B" :[3,5,7,9]})
df["C"]= df["A"] + df["B"]            # in this we were creating a new table by using both pevious two
df

   A  B   C
0  2  3   5
1  4  5   9
2  6  7  13
3  8  9  17

In [ ]:
df=pd.DataFrame({"A": [2,4,6,8],"B" :[3,5,7,9]})
df["C"]= df["A"] + df["B"]            # in this we were creating a new table by using both pevious two  and in this we will use try and type methord
df["try"] = df["A"]>4
df["type"] = df["C"]<5
df

   A  B   C    try   type
0  2  3   5  False  False
1  4  5   9  False  False
2  6  7  13   True  False
3  8  9  17   True  False

In [ ]:
df = pd.DataFrame({"A": [1,2,3,4]})
df.insert(1, "column",df["A"])
df.insert(2,"name2", ["a","b","c","d"])
df

   A  column name2
0  1       1     a
1  2       2     b
2  3       3     c
3  4       4     d

## Dataset upload
- Dataset view {(null, info,sample, size, head,tail etc)}                             
- Missing Values Handle                                                    
- Duplicates Values                                                         
- Standardise Column                                                       
- Data type check                                                          
- Text Clean                                                               
- Categery                                                                 
- Transformation(add/remove column)                                         
- Save in csv file