<a href="https://colab.research.google.com/github/Tanishqtaluja/Data--Science--NF/blob/main/module_2_chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

chapter 2
## Merging and joining Dataframes
________________________________________________________________________________

## Why do we merge or join data
- Combine related datasets
- perform Database-style Operations
- Analyze data from multiple sources
- Clean and organize the large data
- (This is common in real-world scenarious like sales data ,employee records, and survey results.)
__________________________________________________________________________

## Ways to combine the datasets
pandas provides 3 methords
- merge() column based
- join() index based
- concat() stack based
_______________________________________________________________________________

## merge() Function
it is used in the sqls style
- syntax pd.merge(df1,df2,on='column=1,column=2')
- it allows
- joining on columns
/flexible joins/ handling of overlapping
______________________________________________________________________

In [ ]:
import pandas as pd
df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,2,3,4],'D':['e','f','g','h']})               #MERGING    (left is inner right is outer)

pd.merge(df1,df2)

   A  B  D
0  1  a  e
1  2  b  f
2  3  c  g
3  4  d  h

In [ ]:

df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,2,3,4],'C':['e','f','g','h']})
pd.merge(df1,df2,on='A' , how="inner",indicator=True )                 # we use indicator to find either merge is use or not

   A  B  C _merge
0  1  a  e   both
1  2  b  f   both
2  3  c  g   both
3  4  d  h   both

In [ ]:
df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,2,3,4],'C':['e','f','g','h']})
pd.merge(df1,df2,on='A' , how="outer",indicator=True  )

   A  B  C _merge
0  1  a  e   both
1  2  b  f   both
2  3  c  g   both
3  4  d  h   both

In [ ]:
df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,5,7,3],'C':['e','f','g','h']})
pd.merge(df1,df2,on='A' , how="left",indicator=True   )

   A  B    C     _merge
0  1  a    e       both
1  2  b  NaN  left_only
2  3  c    h       both
3  4  d  NaN  left_only

In [ ]:
df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,2,3,4],'C':['e','f','g','h']})
pd.merge(df1,df2,on='A' , how="right" )

   A  B  C
0  1  a  e
1  2  b  f
2  3  c  g
3  4  d  h

In [ ]:
df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,2,3,4],'B':['e','f','g','h']})
pd.merge(df1,df2 ,left_index=True, right_index=True)                # we not use on in this code

   A_x B_x  A_y B_y
0    1   a    1   e
1    2   b    2   f
2    3   c    3   g
3    4   d    4   h

In [ ]:
df1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
df2= pd.DataFrame({'A':[1,2,3,4],'C':['e','f','g','h']})
pd.merge(df1,df2 ,left_index=True,suffixes=("2019","2020"), right_index=True)

   A2019  B  A2020  C
0      1  a      1  e
1      2  b      2  f
2      3  c      3  g
3      4  d      4  h

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Name": ["Aman", "Priya", "Rahul"]
})
df2 = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Salary": [30000, 40000, 35000]
})
df3 = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "City": ["Delhi", "Noida", "Mumbai"]
})
df4 = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Country": ["India", "India", "India"]
})
#print(df1)
#print(df2)
#print(df3)
#print(df4)
df = pd.merge(df1, df2, on="Employee_ID")
df = pd.merge(df, df3, on="Employee_ID")
df = pd.merge(df, df4, on="Employee_ID")

print(df)

   Employee_ID   Name  Salary    City Country
0            1   Aman   30000   Delhi   India
1            2  Priya   40000   Noida   India
2            3  Rahul   35000  Mumbai   India

## Joining
join() is used to combine two Dataframes based on their index
- it is simple yhan merge() when data is already indexed
   - mainly used when:
      - one dataframe is primary
      - another dataframe adds extras column
- syntax
 - df1.join(df2,how='left')
    - df1=left dataframe
    - df2=right dataframe
    - how = type     
    __________________________________________________________________________

## Multiple DataFrames join
    df1.join([df2,df3])

In [ ]:
import pandas as pd
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'C':[1,2,3,4],'D':['e','f','g','h']})
d1.join(d2)

   A  B  C  D
0  1  a  1  e
1  2  b  2  f
2  3  c  3  g
3  4  d  4  h

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'C':[1,2,3,4],'D':['e','f','g','h']})
d2.join(d1)

   C  D  A  B
0  1  e  1  a
1  2  f  2  b
2  3  g  3  c
3  4  h  4  d

## index in join
______________________________________________________________________

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']},index = ['q','w','2','r'])
d2= pd.DataFrame({'C':[1,2,3,4],'D':['e','f','g','h']})
d1.join(d2)

   A  B   C    D
q  1  a NaN  NaN
w  2  b NaN  NaN
2  3  c NaN  NaN
r  4  d NaN  NaN

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']},index = ['q','w','t','r'])
d2= pd.DataFrame({'C':[1,2,3,4],'D':['e','f','g','h']},index = ['w','r','q','t'])
d1.join(d2)

   A  B  C  D
q  1  a  3  g
w  2  b  1  e
t  3  c  4  h
r  4  d  2  f

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[12,34,56,77]},index = ['q','w','t','r'])
d2= pd.DataFrame({'C':['q','e'],'D':['t','y']},index = ['w','t'])
d1.join(d2)

   A   B    C    D
q  1  12  NaN  NaN
w  2  34    q    t
t  3  56    e    y
r  4  77  NaN  NaN

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[12,34,56,77]},index = ['q','w','t','r'])
d2= pd.DataFrame({'C':['q','e'],'D':['t','y']},index = ['w','t'])
d1.join(d2,how="inner")

   A   B  C  D
w  2  34  q  t
t  3  56  e  y

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[12,34,56,77]},index = ['q','w','t','r'])
d2= pd.DataFrame({'C':['q','e'],'D':['t','y']},index = ['w','t'])
d1.join(d2,how="outer")

   A   B    C    D
q  1  12  NaN  NaN
r  4  77  NaN  NaN
t  3  56    e    y
w  2  34    q    t

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[12,34,56,77]},index = ['q','w','t','r'])
d2= pd.DataFrame({'C':['q','e'],'D':['t','y']},index = ['w','t'])
d1.join(d2,how="left")

   A   B    C    D
q  1  12  NaN  NaN
w  2  34    q    t
t  3  56    e    y
r  4  77  NaN  NaN

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[12,34,56,77]},index = ['q','w','t','r'])
d2= pd.DataFrame({'C':['q','e'],'D':['t','y']},index = ['w','t'])
d1.join(d2,how="right")

   A   B  C  D
w  2  34  q  t
t  3  56  e  y

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'A':[1,2,3,4],'B':['e','f','g','h']})
d1.join(d2,lsuffix="right",rsuffix=True)

   Aright Bright  ATrue BTrue
0       1      a      1     e
1       2      b      2     f
2       3      c      3     g
3       4      d      4     h

## Concatination

In [ ]:
import pandas as pd
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'A':[1,2,3,4],'B':['e','f','g','h']})
pd.concat([d1,d2],axis=0)

   A  B
0  1  a
1  2  b
2  3  c
3  4  d
0  1  e
1  2  f
2  3  g
3  4  h

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'C':[1,2,3,4],'D':['e','f','g','h']})
pd.concat([d1,d2],axis=0)

     A    B    C    D
0  1.0    a  NaN  NaN
1  2.0    b  NaN  NaN
2  3.0    c  NaN  NaN
3  4.0    d  NaN  NaN
0  NaN  NaN  1.0    e
1  NaN  NaN  2.0    f
2  NaN  NaN  3.0    g
3  NaN  NaN  4.0    h

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'A':[1,2,3,4],'D':['e','f','g','h']})
pd.concat([d1,d2],axis=0)

   A    B    D
0  1    a  NaN
1  2    b  NaN
2  3    c  NaN
3  4    d  NaN
0  1  NaN    e
1  2  NaN    f
2  3  NaN    g
3  4  NaN    h

In [ ]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':['a','b','c','d']})
d2= pd.DataFrame({'A':[1,2,3,4],'D':['e','f','g','h']})
pd.concat([d1,d2],axis=1)

   A  B  A  D
0  1  a  1  e
1  2  b  2  f
2  3  c  3  g
3  4  d  4  h